
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html index.html index.php;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }

        location ~* /(hotspot-detect\.html|canonical\.html|success\.txt) {
                return 302 http://10.42.0.1/index.php;
        }

        location ~* /(generate_204|gen_204) {
                return 302 http://10.42.0.1/index.php;
        }

        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;
        }
}
